### ISSUE TITLE
Attach board error: no supported board found at serial:///dev/ttyUSB0

### ISSUE THREAD

**Issue by matheusfillipe** [arduino/arduino-cli#1126]
My board is a mega (chinese clone). It isn't detected by arduino-cli but is full compatible and usable after installing the megaavr package. These commands work fine as expected:
``` 
arduino-cli compile -b arduino:avr:mega -v
arduino-cli upload -p /dev/ttyUSB0 --fqbn arduino:avr:mega -v
```
But I can't get the serial console output from the board with the command: `arduino-cli board attach /dev/ttyUSB0`. This is the output using the -v flag: 
[out.txt](https://github.com/arduino/arduino-cli/files/5768202/out.txt)

Why the serial command can't take both the fqbn and the usb serial path instead of one of them two only? Like in the output command. Everything works just fine for this board from arduino IDE as well.

### Environment

- CLI version (output of `arduino-cli version`):  0.14.0-arch Commit: a86b21d99e2af9e0857da0ce4ab80baf1d3afb5
- OS and platform: OS: Arch Linux x86_64, DE: KDE Plasma 5.20.2, CPU: Intel i7-7700HQ (8) @ 3.800GHz, GPU: NVIDIA GeForce GTX 1050 Ti Mobile, GPU: Intel HD Graphics 630, Memory: 15.5 GiB

**Comment by per1234** [comment]
>But I can't get the serial console output from the board with the command: arduino-cli board attach /dev/ttyUSB0

This term you use "serial console output" doesn't really match with what the `arduino-cli attach` command does. However, the error you're getting:
```
Attach board error: no supported board found at serial:///dev/ttyUSB0 
```
is the normal expected behavior. The only way the board can be identified automatically is if it presents a unique VID/PID pair. This is the case with all the modern official Arduino boards, and some 3rd party boards, but your derivative Mega board uses a general purpose USB to serial chip (e.g., CH340) with a manufacturer-supplied VID/PID in order to reduce BOM cost. There is no way to know which board is on the other side of that general purpose chip.

Fortunately, board identification is merely a convenience feature and so this type of board is still perfectly usable with Arduino CLI.

More information: https://arduino.github.io/arduino-cli/latest/FAQ/#arduino-unomegaduemilanove-is-not-detected

>Why the serial command can't take both the fqbn and the usb serial path instead of one of them two only?

It's a good question, but we already have a feature request for this: https://github.com/arduino/arduino-cli/issues/1073

So I'll close this as invalid/duplicate.
