### ISSUE TITLE
Arduino Nano 33 BLE Sense: board does not get detected when connected

### ISSUE THREAD

**Issue by happysalada** [arduino/arduino-cli#1295]
## Bug Report
connecting the board to the usb port on a macos, arduino-cli does not detect it
board: Arduino Nano 33 BLE Sense
host: macOS 10.15.7 (19H524)
arduino-cli alpha Version: 0.18.1 commit b3cf8e19b801b2855ccd2a18c69c673315839231

### Current behavior

```
arduino-cli core install arduino:nrf52
arduino-cli board list
```

outputs
```
Port                            Type        Board Name FQBN Core
/dev/cu.Bluetooth-Incoming-Port Serial Port Unknown
```
No matter if the board is connected to the laptop or not

### Expected behavior

`arduino-cli board list` returns the nano 33 BLE sense board.

open to testing things

**Comment by per1234** [comment]
Thanks for your interest in this open source project @happysalada. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there:

https://forum.arduino.cc/

If we end up determining that your problem is caused by a bug in Arduino CLI, I'll be happy to reopen this issue.
