### ISSUE TITLE
SAM is not available on aarch64

### ISSUE THREAD

**Issue by Kakcalu13** [arduino/arduino-cli#1339]
## Bug Report
![image](https://user-images.githubusercontent.com/65916520/123977361-28e1f080-d97c-11eb-91f5-c7c9aad16708.png)

### Current behavior

```
ubuntu@ubuntu:~/arduino-cli$ arduino-cli core install arduino:sam
Downloading packages...
Error during install: tool arduino:arm-none-eabi-gcc@4.8.3-2014q1 not available for the current OS
ubuntu@ubuntu:~/arduino-cli$ 
```
I need it for arduino DUE via RPI.

### Expected behavior

It should be added just like this laptop:
![image](https://user-images.githubusercontent.com/65916520/123978938-81fe5400-d97d-11eb-9ad3-4cb1fcdab171.png)

### Environment

- CLI version (output of `arduino-cli version`):
- OS and platform:
![image](https://user-images.githubusercontent.com/65916520/123979337-de617380-d97d-11eb-9427-33283b94a8e8.png)
This is raspberry pi 3 model b+

### Additional context
AVR and SAMD were downloaded without any issue, but not SAM. Do you know why did this happen? Is SAM considered as 3rd party?

**Comment by per1234** [comment]
Hi @Kakcalu13. Thanks for your interest in this open source project.
>Do you know why did this happen?

It's because the Arduino SAM Boards platform is using old tools versions from before there was any need to build them for 64 bit ARM Linux.

This was previously discussed at https://github.com/arduino/Arduino/issues/10579. If you check the links off of that, you might discover a workaround.

>Is SAM considered as 3rd party?

No, it's one of the official Arduino boards platforms.

Since this issue is not related to Arduino CLI, I'll go ahead and close this as off topic for this repository.

**Comment by mwimmer88** [comment]
here i post a workaround using an inoffical package provieded by per1234

https://github.com/arduino/Arduino/issues/10579#issuecomment-2595231603
