### ISSUE TITLE
Need assistance tracking down FQBNs for boards

### ISSUE THREAD

**Issue by scottchiefbaker** [arduino/arduino-cli#138]
I came to Github to create an issue asking for the FQBN for an Arduino Nano with the "old" bootloader. Luckily I was able to find it in an [old issue](https://github.com/arduino/arduino-cli/issues/29).

I'm working on a similar project which is a simple `Makefile` wrapper of the [Arduino 1.5+ CLI](https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc) commands. My question is, what is the proper way to track down the FQBN of a given board, and any potential CPU flags for variants?

I'm happy to come here and post an issue every time I run in to one, but that puts more work on you. Is there documentation somewhere that talks about FQBNs? Is there a way that I can read them from the IDE preferences?

**Comment by per1234** [comment]
>what is the proper way to track down the FQBN of a given board, and any potential CPU flags for variants?

For a board without custom menu options, you can get it from `arduino-cli board listall`, but this does not provide the complete FQBN in the case of boards like the Nano which have custom menus. When the menu option is not specified in the FQBN, arduino-cli [should use the default value](https://github.com/arduino/arduino-cli/issues/23), but this is not always what you want.

You can determine the FQBN by looking at boards.txt. In the case of the Nano, you can see the option id `cpu` has three options:
- `atmega328`
- `atmega328old`
- `atmega168`

https://github.com/arduino/ArduinoCore-avr/blob/1.6.21/boards.txt#L141-L184
```
## Arduino Nano w/ ATmega328P
## --------------------------
nano.menu.cpu.atmega328=ATmega328P

nano.menu.cpu.atmega328.upload.maximum_size=30720
nano.menu.cpu.atmega328.upload.maximum_data_size=2048
nano.menu.cpu.atmega328.upload.speed=115200

nano.menu.cpu.atmega328.bootloader.low_fuses=0xFF
nano.menu.cpu.atmega328.bootloader.high_fuses=0xDA
nano.menu.cpu.atmega328.bootloader.extended_fuses=0xFD
nano.menu.cpu.atmega328.bootloader.file=optiboot/optiboot_atmega328.hex

nano.menu.cpu.atmega328.build.mcu=atmega328p

## Arduino Nano w/ ATmega328P (old bootloader)
## --------------------------
nano.menu.cpu.atmega328old=ATmega328P (Old Bootloader)

nano.menu.cpu.atmega328old.upload.maximum_size=30720
nano.menu.cpu.atmega328old.upload.maximum_data_size=2048
nano.menu.cpu.atmega328old.upload.speed=57600

nano.menu.cpu.atmega328old.bootloader.low_fuses=0xFF
nano.menu.cpu.atmega328old.bootloader.high_fuses=0xDA
nano.menu.cpu.atmega328old.bootloader.extended_fuses=0xFD
nano.menu.cpu.atmega328old.bootloader.file=atmega/ATmegaBOOT_168_atmega328.hex

nano.menu.cpu.atmega328old.build.mcu=atmega328p

## Arduino Nano w/ ATmega168
## -------------------------
nano.menu.cpu.atmega168=ATmega168

nano.menu.cpu.atmega168.upload.maximum_size=14336
nano.menu.cpu.atmega168.upload.maximum_data_size=1024
nano.menu.cpu.atmega168.upload.speed=19200

nano.menu.cpu.atmega168.bootloader.low_fuses=0xff
nano.menu.cpu.atmega168.bootloader.high_fuses=0xdd
nano.menu.cpu.atmega168.bootloader.extended_fuses=0xF8
nano.menu.cpu.atmega168.bootloader.file=atmega/ATmegaBOOT_168_diecimila.hex

nano.menu.cpu.atmega168.build.mcu=atmega168
```
More information:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification#custom-board-menus

My current approach in the case of boards with custom Tools menus is to do a compilation in the Arduino IDE for the specific board configuration I want with **File > Preferences > Show verbose output during: compilation** enabled, and then copy the FQBN from the first line of the output in the black console window at the bottom of the Arduino IDE window. Quite crude, but it seems the fastest and least error-prone solution for me.

>Is there a way that I can read them from the IDE preferences?

Not very easily, since the custom menu selections for every board you've ever used are all stored in preferences.txt. The only way you could practically do this is by clearing all the previous data out of preferences.txt before starting the IDE, selecting the desired board configuration, and then exiting the Arduino IDE to save the data to preferences.txt. I think my clumsy method is preferable to that.

There is a boards.txt parser Python script proposed for addition to the ESP8266 hardware package that extracts the FQBN components from boards.txt here: https://github.com/esp8266/Arduino/pull/5657. That provides the option of [human readable text output](https://gist.github.com/d-a-v/481ac17ea9becf99bdcf239fe2415837) or [machine readable JSON output](https://gist.github.com/d-a-v/c3cceb80d61d509908d1061f6f85b9df).

Now that I reconsider that Python script, I think it's a bit flawed for universal usage because it will only truly be useful for packages like ESP8266 that use the same options for all boards. Other packages like Arduino AVR Boards only provide certain options for certain boards. I'll provide some feedback to the author about this.

It might be nice for arduino-cli to provided something to show the available menu options for each board, in addition to the partial FQBNs provided by `arduino-cli board listall`.

**Comment by scottchiefbaker** [comment]
This was extremely helpful, and exactly what I needed. Thank you.
