### ISSUE TITLE
FQBN not being found when connected through FTDI board 

### ISSUE THREAD

**Issue by apozharski** [arduino/arduino-cli#149]
I am trying to use the arduino-cli with a Pro-mini board. The board itself needs to be connected through an FTDI board. I have installed the `arduino:avr` core which provides `arduino:avr:pro` which should work for the board. However when calling `arduino-cli board list` the board's FQBN is blank and the board type is unknown.

**Comment by per1234** [comment]
This is the expected behavior for any board that uses an FTDI or any other USB to TTL serial adapter chip that has a generic VID/PID. There is not way for arduino-cli to determine the FQBN for these boards as they provide no unique identifying information. arduino-cli has no way of knowing what is on the other side of that FTDI board.

Closing as duplicate of https://github.com/arduino/arduino-cli/issues/37
