### ISSUE TITLE
Digispark upload

### ISSUE THREAD

**Issue by BetterCall** [arduino/arduino-cli#1630]
### Environment

- CLI version (output of `arduino-cli version`):0.20.2 commit 13783819 date 2021-12-09t13:32
- OS and platform: windows 10  

### Current behavior
`arduino-cli.yaml` is ok 
```yaml
Additional_urls : 
  - http://digistump.com/package_digistump_index.json
```
Packages et boards downloaded with `arduino-cli.exe core install digistump:avr`

arduino-cli.exe compile -b digistump:avr:digispark-tiny
arduino-cli.exe upload -b digistump:avr:digispark-tiny 

If you never compiled and uploaded sketch to digispark with the arduino gui the upload command runs without uploading or returning error 
Cmd :
Running Digispark Uploader …
Plug in device now … ( will timeout in 60 seconds ) 

At this point, cmd just end without timeout, but once you set preference in the GUI added additional boards urls, board, compiled and uploaded with GUI
The command `arduino-cli.exe upload -b digistump:avr:digispark-tiny` works like a charm 

### Reproduce 
Never uploaded sketch to digispark with GUI

download arduino-cli.exe 
Add http://digistump.com/package_digistump_index.json to the `additional_url`

`arduino-cli.exe core install digistump:avr `

Create .ino 
`arduino-cli.exe compile -b digistump:avr:digispark-tiny`
`arduino-cli.exe upload -b digistump:avr:digispark-tiny`

### Additional context 

The application embed arduino-cli in electron app so upload works only if user already upload to digispark before

**Comment by per1234** [comment]
Hi @BetterCall. If you run the `arduino-cli upload` command with the `--verbose` flag, you can see the upload command generated by the `digistump:avr` boards platform.

It will look something like this:
```
"C:\Users\per\AppData\Local\Arduino15\packages\digistump\tools\micronucleus\2.0a4/launcher" -cdigispark --timeout 60 -Uflash:w:C:\Users\per\AppData\Local\Temp\arduino-sketch-5162AF43A5C9EEB136B73635BA92A5B1/Foo.ino.hex:i
```
If you run that command directly from the command line, you will get the same result of it exiting immediately rather than waiting for the board to be connected.

This means that the problem is with the upload tool provided by the `digistump:avr` boards platform, not a problem with Arduino CLI. Unfortunately, DigiStump ceased supporting their software years ago, so you won't be able to get a fix from them. 

Fortunately, the Arduino community has stepped in to carry on this project. You can find an excellent fork here:
https://github.com/ArminJo/DigistumpArduino
and ATTinyCore also has recently added the Micronucleus support:
https://github.com/SpenceKonde/ATTinyCore/blob/master/avr/extras/UsingMicronucleus.md
I think you will find success with either of those platforms.
