### ISSUE TITLE
Allow library dependencies to install from git and zip

### ISSUE THREAD

**Issue by framinlab** [arduino/arduino-cli#1772]
### Describe the request

arduino-cli supports installing libraries from the central repo, git URLs, and zip files. When creating a library, the library.properties file has a `depends=` field that only supports central repo libraries.

Easiest way would be to check each entry in a `depends` entry and see if it is a local or remote URL and whether it ends with a .zip or a .git ending, then use the same mechanism as arduino-cli to install them.

For example, in library.properties, it could look like:

```
...
depends=ArduinoHttpClient, https://github.com/myproj/myproj.git,./localpath/mylib.zip,ArduinoJson
```

Additionally, in the IDE Library Manager, allow support for both adding a .ZIP file (like the Include Library > Add .zip library menu, as well as entering remote github URL.

This will make the IDE feature-compatible with the CLI.

### Describe the current behavior

Installing a library from github is not supported in the IDE even though it is in arduino-cli. 
The feature should also be supported in the `depends` field of library.properties.

### Arduino IDE version

2.0.0-rc7

### Operating system

macOS

### Operating system version

Monterey 12.4

### Additional context

Arduino CLI supports:

arduino-cli lib install {library-name}
arduino-cli lib install --git-url https://github.com/mylibrary/mylibrary.git
arduino-cli lib install --zip-path ./mylibrary/library.zip

Also, libraries.properties supports a `depends=` field that currently only accepts registered libraries, but not git-url or zip-path entries.

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by LuKks** [comment]
cc @per1234

> This claim is misleading. Just like Arduino IDE, Arduino CLI does NOT support the inclusion of Git repositories in the depends field of the library.properties file. It does support manual installation of libraries from a Git repository source via the lib install command, but that is a completely different feature so it is misleading to claim an equivalence between these two things.

Yep, it was misleading without realizing because I was thinking that if the IDE is using the CLI then it could easily detect if a item of `depends` it's a Git URL then install it with the CLI feature. If you read the original description of this issue `then use the same mechanism as arduino-cli to install them` he's describing the same idea. And it doesn't matter if it's slower it's a known trade-off, otherwise it would be good to know how much slower because it's probably completely fine

> Nah. This is something a developer would write once in the lifetime of a library. Creating an artificially limiting convention just to save them a few keystrokes doesn't make sense.

I would strongly disagree. It does make sense, I also just followed the NPM conventions (btw they had over a quarter of a trillion downloads last month, not for allowing Git dependencies but they're doing something right)

I think developers would prefer this:

```
name=ota
depends=lukks/crypto, lukks/nvs#branch, gitlab:user/repo
```

(also fine to always require the `github:` prefix, and still allowing full URLs)

Instead of:

```
name=ota
depends=https://github.com/lukks/crypto, https://github.com/lukks/nvs#branch, https://gitlab.com/user/repo
```

It's not about saving keystrokes as in it's not "write once" it's "read many" just like in coding, it's about keeping it simple and readable because it's easy to parse the items to simplify the properties. At the end, I don't mind at all if it's only full URLs, it would still be a win for you if developers could use remote Git URLs

> "Creating an artificially limiting convention ..."

I would say the current `depends` format is _the_ actual artificially limiting convention :sweat_smile: 

> This is false. ESP-IDF is a dependency of the ESP32 boards platforms. It is installed with that platform, and not present when the platform is not installed.

> "... So introducing a dependency on the framework of a specific family of microcontrollers would never be considered."

That's just semantics. The point is that if you're using an ESP32 board, you will have it downloaded so it's practically built-in and it's ignoring the `idf_component.yml` file which maybe it makes sense because you have `library.properties` but then allow us to use remote URLs haha

Anyway, I decided to answer the feedback on the issue because I think it's worth the time to re-explain and insist, even more important considering that someone already requested the feature before. I will insist no more now so it's all good. Thanks for allowing feature requests
