### ISSUE TITLE
arduino-cli core install should install binary tools matching the architecture of the system it is run on

### ISSUE THREAD

**Issue by imrehorvath** [arduino/arduino-cli#1838]
### Describe the request

It would be required that the commands like: `arduino-cli core install arduino:avr` installs the binary tools in the core for the architecture of the system it is executed on. Eg. the bundled binary gcc in the core should be built for arm64 on Apple silicon Macs and not Intel x86_64.

### Describe the current behavior

Currently the `arduino-cli core install arduino:avr` command installs binary tools pre-built for Intel x86_64 on Apple silicon Macs.

### Arduino CLI version

0.26.0

### Operating system

macOS

### Operating system version

macOS Monterey 12.5

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the feature was still missing when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @imrehorvath. Thanks for your request.

Arduino CLI already does pick the best match of the available variants of the tool for the host architecture. If the package maintainer has produced a build for the exact architecture of the host then that will be used. If not, it will use a compatible variant.

The reason you get tools built for macOS x86-64 is because none are available for Apple M1 architecture. If such tool builds are produced, they will start being used without any change in Arduino CLI. Until then, it is better to use the x86-64 variants, which are perfectly compatible with Apple M1 machines courtesy of [Rosetta 2](https://en.wikipedia.org/wiki/Rosetta_(software)#Rosetta_2).

You can see the tool selection code here:

https://github.com/arduino/arduino-cli/blob/9fe8560e917ec097b4454f462363e049358017c0/arduino/cores/tools.go#L126-L213
