### ISSUE TITLE
why config folder is ~/.arduino15 ?

### ISSUE THREAD

**Issue by ololosha228** [arduino/arduino-cli#186]
can i make it custom? why not in /etc? why not in ~/.local/etc? i have billion of dotfiles and dotfolders in my home folder, why i need have another? and why is it 15?)

**Comment by per1234** [comment]
>can i make it custom?

Yes. You can set it via the `arduino_data` field in your arduino-cli.yaml.

>why is it 15

Because the folder was originally called `.arduino` back in the Arduino IDE 1.0.x days, but then some significant changes were made to the Arduino IDE back when the version number was 1.5.x so they wanted to allow the IDE versions to use separate data folders to avoid any possible conflicts.

Support questions like this are more appropriate for the [Arduino Forum](http://forum.arduino.cc/). This issue tracker is intended to be used for reporting bugs and feature requests.
