### ISSUE TITLE
.s file do not get copied into build directory for project with ULP code

### ISSUE THREAD

**Issue by 2dom** [arduino/arduino-cli#1977]
### Describe the problem

When trying to compile ULP code, the .s file is not copied from the source directory into the build directory. Hence the compile fails with 'undefined reference to' errors. The linking succeeds if the file is copied into the build directory by hand. 

### To reproduce

Compile any ULP example project  

### Expected behavior

Compile succeeds

### Arduino IDE version

2.01

### Operating system

macOS

### Operating system version

Ventura 13.0.1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by matthijskooijman** [comment]
From a quick glance, ULP is the ultra-low-power coprocessor in the ESP32? That is probably programmed using a different kind of assembly language than the regular ESP32 assembly, so that explains why it must have a different file extension. But I do not think arduino-cli has any support for such auxiliary extensions nor coprocessors, so I guess this is something for the ESP32 core to solve somehow. Maybe try reporting this bug there?

**Comment by per1234** [comment]
I understand now:
https://github.com/duff2013/ulptool#readme

The **ulptool** relies on undefined behavior of older versions of the Arduino build system, where correct file extension case was not enforced when copying files from the sketch folder to the build folder. This actually stopped working at Arduino IDE 1.8.14:
https://github.com/duff2013/ulptool/issues/74

I found it was possible to copy the `.s` files using a [build hook](https://arduino.github.io/arduino-cli/latest/platform-specification/#pre-and-post-build-hooks-since-arduino-ide-165) (which are [already used](https://github.com/duff2013/ulptool/blob/master/platform.local.txt) by the ulptool project). I submitted a pull request for the fix: https://github.com/duff2013/ulptool/pull/90

If you don't want to wait for the PR to be merged, you can apply the simple patch to your `platform.local.txt` file:

https://github.com/duff2013/ulptool/pull/90/files

Otherwise, you can use Arduino IDE 1.8.13 as a workaround. The download links are listed here:

https://www.arduino.cc/en/software/OldSoftwareReleases#arduino-18x
