### ISSUE TITLE
`arduino-cli` reports outdated version on Arch Linux unnecessarily

### ISSUE THREAD

**Issue by UtkarshVerma** [arduino/arduino-cli#2355]
### Describe the problem

On Arch Linux, `arduino-cli` version is suffixed with an `arch` label which results in `v0.34.2` being mentioned as `v0.34.2-arch`. This throws off this tool's version-matching logic where it thinks it is outdated.

### To reproduce

```console
$ arduino-cli board list
Port         Protocol Type              Board Name FQBN Core
/dev/ttyUSB0 serial   Serial Port (USB) Unknown



A new release of Arduino CLI is available: 0.34.2-arch → 0.34.2
https://arduino.github.io/arduino-cli/latest/installation/#latest-packages
```

### Expected behavior

No version warning should be given.

### Arduino CLI version

0.34.2

### Operating system

Linux

### Operating system version

6.5.5

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @UtkarshVerma. I guess you installed Arduino CLI from a package repository instead of using the official builds as obtained by following the documentation here:

https://arduino.github.io/arduino-cli/dev/installation/

You will need to report this problem to the maintainer of the 3rd party modified package. Arduino does not maintain that package and we only provide support for the builds that are installed using one of the officially methods.
