### ISSUE TITLE
Make `upload.port.*` properties available in compile patterns

### ISSUE THREAD

**Issue by Silver-Fang** [arduino/arduino-cli#2362]
### Describe the request

This issue has already been raised [in the forum](https://forum.arduino.cc/t/compile-time-definition-for-serial-port), but my application scenario is slightly different from his. My computer is connected to multiple boards on different COM ports. They have basically the same model and program to run, but the devices they operate are plugged into different pins.

I would like to have a compile-time macro definition that indicates the COM port currently selected by the IDE. For example, if I had a compile-time attached macro definition "COM", I could code:
```C++
#define Pin constexpr uint8_t
#if COM == 3
Pin pBlueLed = 11;
Pin pActiveBuzzer = 52;
#elif COM == 4
Pin pBlueLed = 8;
Pin pActiveBuzzer = 22;
#elif COM == 5
Pin pBlueLed = 11;
Pin pActiveBuzzer = 22;
#endif
```
This way I don't need to change the pin number every time to upload to a different COM port. I can write the corresponding pin numbers of all COM ports, and then the compiler preprocessing automatically selects the correct pin configuration.

### Describe the current behavior

There currently seems to be no way to get COM numbers in the code.

### Arduino IDE version

2.2.1

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @Silver-Fang. I transferred this to the issue tracker for [**Arduino CLI**](https://arduino.github.io/arduino-cli/latest/) because it is Arduino CLI that provides the sketch compilation capability to Arduino IDE under the hood.

Arduino's approach to [the boards platform system](https://arduino.github.io/arduino-cli/dev/platform-specification) is to provide a powerful and flexible framework and give the platform developers the freedom to choose what to build on that framework.

So hardcoding such a macro into the platform framework would be a terrible idea. Instead what would be done is to make the port selection data available via platform properties. The platform developer can then add a `-D` flag to the compilation command patterns to set the macro (e.g., `-DARDUINO_UPLOAD_PORT_ADDRESS="{upload.port.address}"`).

In fact the platform frame work already provides such properties:

https://arduino.github.io/arduino-cli/dev/platform-specification/#serial-port

However, those properties are only available for use in the upload-related command patterns.

**Arduino CLI** separates the [compilation](https://arduino.github.io/arduino-cli/dev/commands/arduino-cli_compile/) and [upload](https://arduino.github.io/arduino-cli/dev/commands/arduino-cli_upload/) operations. The port is only specified during the upload operation (e.g., `arduino-cli upload --port COM42 ...`). The user can specify port data during a compilation operation in order to support [the `--upload` flag](https://arduino.github.io/arduino-cli/dev/commands/arduino-cli_compile/#options), which causes a sequence of compilation+upload similar to how an upload is performed when using Arduino IDE (even though Arduino IDE actually runs two separate commands in sequence).
