### ISSUE TITLE
Older `.msi` install takes prioritiy over updated `scoop` install

### ISSUE THREAD

**Issue by aliphys** [arduino/arduino-cli#2397]
### Describe the problem

I had previously (0.32.2) installed `arduino-cli` via the .msi package. I then used the `scoop` package manager to install and update to the latest version (0.34.2). However, it is stuck on the version installed by the .msi manager. I cannot find the location of the arduino-cli.exe file.

There is no .msi file for the latest release (0.34.2) (edit: The .msi installer is not present on the Installation page [here](https://arduino.github.io/arduino-cli/0.21/installation/). It is accessible however in the release for [0.34.2](https://github.com/arduino/arduino-cli/releases/tag/0.34.2)). Uninstalling the installer from `Add or Remove Programs` was however a solution. 

### To reproduce

1. Install https://github.com/arduino/arduino-cli/releases/download/0.32.2/arduino-cli_0.32.2_Windows_64bit.ms
2. Install scoop in Windows PowerShell
```
Set-ExecutionPolicy RemoteSigned -Scope CurrentUser # Optional: Needed to run a remote script the first time
irm get.scoop.sh | iex
```
3. Update scoop `scoop update`
4. Install the arduino-cli `scoop install arduino-cli`
5. Check for update `scoop update arduino-cli`. The version of the cli that is displayed should be 0.34.2 at time of writing
```
PS C:\Users\user> scoop update arduino-cli
arduino-cli: 0.34.2 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
```
7. This is the output of `arduino-cli version`
```
PS D:\Github\Arduino\Arduino_UnifiedStorage> arduino-cli version
arduino-cli.exe  Version: 0.32.2 Commit: 2661f5d9 Date: 2023-04-12T09:41:59Z
```
8. When the installer is removed, the scoop version (which is up to date) is identified
```
PS D:\Github\Arduino\Arduino_UnifiedStorage> arduino-cli version    
arduino-cli.exe  Version: 0.34.2 Commit: 963c1a76 Date: 2023-09-11T10:05:41Z
```

### Expected behavior

The latest version of `arduino-cli` is used if both are avaliable on the path.

### Arduino CLI version

0.34.2

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

**Comment by umbynos** [comment]
Hi @aliphys,
Unfortunately, the @arduino/team_tooling does not maintain the scoop installer: https://github.com/ScoopInstaller/Main/commits/master/bucket/arduino-cli.json, so we don't know how it works. One thing I know is that both installation can coexist, since the tools are installed in two different destinations.

Actually, to uninstall the MSI package you are supposed to use `Add or Remove Programs` utility :smile: 

> The latest version of arduino-cli is used if both are avaliable on the path.
Unluckily, it does not work like that :sweat:

>  1.  Install https://github.com/arduino/arduino-cli/releases/download/0.32.2/arduino-cli_0.32.2_Windows_64bit.ms
>  2. Install scoop in Windows PowerShell

Here lies the problem: by performing 1. the binary path is added to the [`$PATH` env variable](https://en.wikipedia.org/wiki/PATH_(variable)). After completing 2. the path in which scoop installs programs is added to the `$PATH` too. **But right after the msi one**.

Both version of the program are available in the PATH, but the MSI version is higher in the list, thus takes precedence. When you run a command in the shell the first entry in the `$PATH` that matches the command is the one used. So you cannot "use the latest" if you install a command using two different sources.

I'm afraid there is nothing that we can do for this issue

**Comment by umbynos** [comment]
One last thing: The MSI installer option is listed in the installation page: https://arduino.github.io/arduino-cli/latest/installation/#latest-release.

So I would close this one

**Comment by aliphys** [comment]
Windows applies higher priority to the `PATH` for the MSI install, compared to the Scoop install. Uninstalling MSI version is a reasonable solution.

As I understand, solving `PATH`/version conflicts is not a priority right now, so closing issue as not planned

**Comment by umbynos** [comment]
It's slightly different from that:
> Windows applies higher priority to the PATH for the MSI install, compared to the Scoop install.

Actually, it depends on the order **the user** adds the paths in the $PATH variable.
That's why we cannot do anything to fix it.
