### ISSUE TITLE
Track installed cores with a dedicated index file

### ISSUE THREAD

**Issue by masci** [arduino/arduino-cli#252]
## Bug Report

This is for a bug afflicting the IDE, see https://github.com/arduino/Arduino/issues/8936 for details. Let's double check how the same issue impacts the CLI and whether the solution being proposed might work here as well.

**Comment by per1234** [comment]
Using arduino-cli 5cca8e278bee6f1c77aec8abe7f96af55011bcc7

### Regarding the issue of the installed boards disappearing if the download of their Boards Manager JSON file fails

What I did to test:
1. Publish a Boards Manager JSON file as a Git Gist.
1. Install a hardware core from that JSON file using `arduino-cli core install`.
1. Delete the Gist to simulate an outage of the JSON file.
1. `arduino-cli core update-index` now outputs the following:
    ```
    Updating index: package_index.json downloaded                                                                                                                                            
    Updating index: package_index.json downloaded                                                                                                                                            
    Updating index: package_asdf_index.json downloaded                                                                                                                                       
    Error: invalid package index in https://gist.githubusercontent.com/per1234/ac3efc0419d3c3a73c262edb7e350ee7/raw/f90a073a1b24823639f211249c01446e8bce5874/package_asdf_index.json: invalid character ':' after top-level value
    Error updating index
    ```

After that, package_asdf_index.json is still present in the data folder and `arduino-cli core list` still shows the hardware core from that JSON file is installed and I'm able to compile for the boards.

So it seems to me that arduino-cli has the correct behavior in this case.

### Regarding the issue of the installed boards disappearing if the entry for the installed release is removed from the JSON file

1. Install the hardware core
2. Remove the entry for the installed version from the JSON file
3. `arduino-cli core update-index`
4. Verify the updated version of the JSON file with the entry for the installed version of the hardware core removed was downloaded.

After that, `arduino-cli core list` still shows the hardware core from that JSON file is installed and I'm able to compile for the boards.

---
Despite these positive findings, @matthijskooijman's idea presented in https://github.com/arduino/Arduino/issues/8936#issuecomment-498203693 of storing the JSON at the time of the board installation is still useful in the event of the JSON file author later removing information relevant to the installation from their file because the `toolsDependencies` information is needed when checking whether any other core has a dependency on tools that that might be removed during a hardware core uninstallation.

**Comment by masci** [comment]
@per1234 thanks for the detailed report, going to turn this issue into a feature request and schedule some work in our backlog to implement the `installed.json` feature.
