### ISSUE TITLE
--zip-path cannot be enabled

### ISSUE THREAD

**Issue by dcrookston** [arduino/arduino-cli#2634]
### Describe the problem

 ```
$ arduino-cli lib install --zip-path ~/src/arduinolibs/libraries/crypto.zip
--git-url and --zip-path are disabled by default, for more information see: https://arduino.github.io/arduino-cli/0.35/configuration/#configuration-keys
```

I went to that URL and there is nothing about the setting to enable --zip-path.  I searched and found this article:

https://forum.arduino.cc/t/arduino-cli-library-installing-error-enable-unsafe-install-is-false/867734

which says to set ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL.  This was already set, but I tried it anyway:

```
$ set ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL=true
$ arduino-cli lib install --zip-path ~/src/arduinolibs/libraries/crypto.zip
--git-url and --zip-path are disabled by default, for more information see: https://arduino.github.io/arduino-cli/0.35/configuration/#configuration-keys
```

So either the error message, or the documentation, or the code, are wrong.

### To reproduce

Install literally anything using the --zip-path flag.

### Expected behavior

It should accept the path I gave it using --zip-path.

### Arduino CLI version

0.35.3 Commit: 95cfd654 Date: 2024-02-19T13:24:25Z

### Operating system

Linux

### Operating system version

Linux raspberrypi 6.6.28+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.28-1+rpt1 (2024-04-22) aarch64 GNU/Linux

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @dcrookston. The person being supported in that forum topic was a Windows user, so the information shared there was specific to Windows cmd. The [`set` command](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/set_1) is used to define environment variables in Windows cmd, but on Linux the command of that name has [a completely different purpose](https://www.man7.org/linux/man-pages/man1/set.1p.html) so if you follow those instructions on a Linux machine the environment variable will not be defined.

On Linux, you must use this command:

```text
export ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL=true
```

Reference:

https://www.man7.org/linux/man-pages/man1/export.1p.html

The methods for defining the configuration key environment variables is already documented in the Arduino CLI configuration documentation:

https://arduino.github.io/arduino-cli/dev/configuration/#environment-variables

So I don't think any action is needed to address this issue (we should add coverage for PowerShell since that has become the primary shell on Windows, but that is a different subject).
