### ISSUE TITLE
Compiling on CentOs 6 (Missing glibc-2.14 and GLIBCXX_3.4.15)

### ISSUE THREAD

**Issue by kzka90** [arduino/arduino-cli#319]
I'm trying to compile a .INO file within my server, I have a 64-bit CentOs 6

At first, it was telling me I needed a higher glibc version than the one I had, so I added the one it was asking to my server, I didn't installed it as the main but as a parallel compiler, everytime I want to use it, I'm doing this:

```
LD_LIBRARY_PATH=/opt/glibc-2.14/lib
export LD_LIBRARY_PATH
```

After setting this glibc version, I tried again to run the compiling code:

`./arduino-cli compile --fqbn esp32:esp32:esp32 test`

But now I'm encountering the following:

```
Build options changed, rebuilding all
/root/.arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/1.22.0-80-g6c4433a-5.2.0/bin/../libexec/gcc/xtensa-esp32-elf/5.2.0/cc1plus: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /root/.arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/1.22.0-80-g6c4433a-5.2.0/bin/../libexec/gcc/xtensa-esp32-elf/5.2.0/cc1plus)
Error: build failed: exit status 1
Error during build
```

Seems that I need a higher version of the libstdc++.so.6 library, it's asking for: **GLIBCXX_3.4.15**

I've searched everywhere on how to install this in CentOs 6 (without compromising my server) and have found nothing.

I have two options:

1. Find a way to use **GLIBCXX_3.4.15** and hope there won't be other missing parts to compile.
2. Find a way to compile the desire code with the libraries my server already have.

Any ideas what to do?

**Comment by facchinm** [comment]
Hi @kzka90 ,
I think you should report the issue to esp32 arduino core repo since the issue is just in their toolchain (https://github.com/espressif/arduino-esp32). `arduino-cli` is statically compiled as every go program to avoid exactly this kind of issues.

Longer explanation: when compiling any program on Linux it gets dynamically linked to libc (and eventually libstdc++ ) if needed. These libraries version the symbol they provide for backwards compatibility (so if the APIs change an older program can run anyway).
The opposite is not true, so if you try to run a program targeting glibc 3.4.15 on an older system it will complain about the missing symbol.
This behaviour can be solved by using this approach https://stackoverflow.com/a/20065096 or by compiling with an "older" toolchain (usually build with ct-ng)
