### ISSUE TITLE
arduino-cli commands not recognized across folders

### ISSUE THREAD

**Issue by MicheleCioccarelli** [arduino/arduino-cli#705]
I recently downloaded the arduino-cli and i was following the official tutorial to get started, but the command line kept saying that it didn't recognize "arduino-cli"
Today i discovered that if I place the file "arduino-cli.exe" in the folder I am working on, everything is fine.
Is this intended?

**Comment by ubidefeo** [comment]
@MicheleCioccarelli 
The `arduino-cli.exe` command should be reachable within your system's search path.
Because on Windows you don't have an installer but just download the `.exe` file you'll have to manually copy it it some path your system can reach easily.
You can take a look at this article (first one which came out of a google search) and it should apply.
Let me know if you sort it out.

@rsora I was surprised this bit about installing on Windows is not part of the doc :)

**Comment by rsora** [comment]
I summon @per1234 to the rescue :smile_cat: 
We could also think about generating a `.msi` installer as I saw [here](https://github.com/cli/cli/blob/master/.github/workflows/releases.yml#L59)

**Comment by ubidefeo** [comment]
documentation is key, but I'll leave the decision to create an `.msi` installer to you.
I don't like that much when it comes to command line tools, but it's just my opinion ;)

**Comment by umbynos** [comment]
Hi @MicheleCioccarelli we now have a MSI installer :partying_face: This installer will also place the binary in the windows PATH env variable.

**Comment by umbynos** [comment]
https://github.com/arduino/arduino-cli/releases/download/0.28.0-rc.1/arduino-cli_0.28.0-rc.1_Windows_64bit.msi
