### ISSUE TITLE
--log-level Debug is documented but not accepted with capital "D"

### ISSUE THREAD

**Issue by ArminJo** [arduino/arduino-cli#714]
### Current behavior
`board listall -v --log-level Debug`

is not accepted, but the usage states:

`--log-level string          Messages with this level and above will be logged. Valid levels are: Trace, Debug, Info, Warning, Error, Fatal, Panic`

instead only

`**board listall -v --log-level debug**`

with **lowercase** "d" is accepted.

**Please change usage or parser to be consistent.**

### Environment

- CLI version (output of `arduino-cli version`): 1.10.0 Commit: ec5c3ed
- OS and platform: windows, linux...

**Comment by per1234** [comment]
Thanks for the report @ArminJo!

This issue was fixed in the command line help by https://github.com/arduino/arduino-cli/pull/653:
```
$ arduino-cli help
...
      --log-level string          Messages with this level and above will be logged. Valid levels are: trace, debug, info, warn, error, fatal, panic

```
but there seems to be a problem with the automated generation of the documentation for the command line interface that's published at https://arduino.github.io/arduino-cli/commands/arduino-cli/, so that page still contains the incorrect information.
