### ISSUE TITLE
Issue with platform tool dependency resolving

### ISSUE THREAD

**Issue by timonsku** [arduino/arduino-cli#915]
This relates to this issue https://github.com/adafruit/ArduinoCore-samd/issues/142
As described in the issue above I had the case where I had to first install the SAMD core provided by Arduino before I got all the necessary tools like bossac installed. Just installing the Adafruit core, even though it defines the same packages (but no download URL because it references the tools provided by Arduino). This behaviour suggest that the IDE did not check the available packages to install bossac but failed to find the defined source.

Which brings me to the question whether or not tool dependency resolving only happens via already installed packages or if it is supposed to look into all the packages available for download to look for all needed tools (e.g. include all the tools defined by official Arduino board packages and everything included via board manager URLs).
The specs here are unclear about the exact behaviour: https://arduino.github.io/arduino-cli/package_index_json-specification/

I have seen this behaviour on all supported platforms.

**Comment by per1234** [comment]
Hi @PTS93. I've tried to investigate this issue, but have not been able to reproduce it. Would you mind providing me with a specific set of steps I can follow to reproduce it? If you're using Arduino CLI, you can just give me the `arduino-cli` commands.

>Which brings me to the question whether or not tool dependency resolving only happens via already installed packages or if it is supposed to look into all the packages available for download to look for all needed tools (e.g. include all the tools defined by official Arduino board packages and everything included via board manager URLs).

The latter. When you install a boards core via Boards Manager (or `arduino-cli core install`), the defined tool dependencies are installed along with the boards core if they are not already installed. So as long as all necessary tool dependencies are defined in the core's package index file (which Adafruit has done correctly), all tools should be installed, regardless of whether any other board cores are installed.

>The specs here are unclear about the exact behaviour: https://arduino.github.io/arduino-cli/package_index_json-specification/

That link provides an outdated version of the documentation. Some small improvements have been made to clarify the workings of the tool dependency system in the package_index.json specification since that time. We do have one or two more improvements in this area on our "to-do" list, but if you check the up to date version of the documentation and have any specific suggestions for improvement, they would be very welcome:
https://arduino.github.io/arduino-cli/dev/package_index_json-specification/

**Comment by PTS93** [comment]
Hi @per1234 . Unfortunately I had the same issue. It was happening very randomly and sometimes months apart.
So I have no specific instructions to reproduce it but it mostly happened on a fresh install of the IDE and the only thing being downloaded was the Adafruit SAMD core.

Could it be that the install will proceed even if some of the tools weren't able to download (e.g. connection timeout during download, permission error during extraction etc..) and all I witnessed was the IDE trying again when I simply choose a different core with the same dependencies? Thats where I would personally start looking into how the IDE behaves when something unexpected happens like a connection timeout. How much does it guarantee that the install went ok and if it knowingly errors out, how clearly does it communicate to the user? Does it revert any changes of a partial install?

**Comment by cmaglie** [comment]
This should be solved by #1887 which add specification on how tool selection should behave in all cases.
