### ISSUE TITLE
Docs incorrectly state that upload will treat -P list as an instruction to list programmers

### ISSUE THREAD

**Issue by PeterWone** [arduino/arduino-cli#967]
### Current behavior

```
arduino-cli upload --fqbn arduino:avr:nano --programmer list
```

Fails to treat `list` as a special symbol.

### Expected behavior

The documentation says it will list available programmers.

### Environment

- CLI version (output of `arduino-cli version`): 0.13.0
- OS and platform: Windows 10

### Additional context

`arduino-cli burn-bootloader --fqbn arduino:avr:nano --programmer list` works as advertised. 

The capability to get a list of supported programmers is available from burn-bootloader, perhaps update the documentation to suggest that.

**Comment by ubidefeo** [comment]
hi @PeterWone 
because this syntax was pretty cumbersome and programmers are part of platform definition and related to a specific board, we introduced a new flag for `boards detail` to just show programmers

`arduino-cli board details -b arduino:avr:uno --list-programmers`

the fact that `burn-bootloader` still has that is a leftover that we'll have to cleanup :) (@silvanocerza )

**Comment by PeterWone** [comment]
In that case this issue is actually about the docs being behind the reality. Thanks for sharing the reality!

**Comment by ubidefeo** [comment]
hey @PeterWone 
you are right, we need to update the documentation.
Than you for pointing it out, some things end up slipping through the cracks :)

**Comment by per1234** [comment]
The documentation has now been corrected by https://github.com/arduino/arduino-cli/pull/982.

Thanks PeterWone!
