### ISSUE TITLE
compile flag -o removed, how to do this in current version?

### ISSUE THREAD

**Issue by harryberlin** [arduino/arduino-cli#983]
### Current behavior

C:\Users\...\Downloads\arduino-cli\arduino-cli.exe compile -b arduino:avr:nano -o C:\temp\MySketch\Release\MYNANO C:\Users\....\MySketch

### Expected behavior

how to use the -o flag with current version?

### Environment

- CLI version (output of `arduino-cli version`): 0.13.0 32bit
- OS and platform: windows 10

**Comment by ubidefeo** [comment]
hi @harryberlin 
I think we lost the short flag format for that at some point, but not sure why (@cmaglie / @silvanocerza ?)
you can use `--output-dir` which has recently gotten some love and works very well for what you need to do :)

**Comment by harryberlin** [comment]
sorry, it's not the same. now, i get a subfolder.
is there a solution to only get the .hex file without bootloader and other without .eep + .elf?
had a workaroudn to compile with -o flag and delete the other not needed files.

**Comment by ubidefeo** [comment]
@harryberlin I've assigned this task
we'll get back to you soon

**Comment by ubidefeo** [comment]
@harryberlin 
We discussed this one and essentially the old `-o` was causing issues because not every 3rd party platform developer follows specs and we had complaints because things just broke.
a few releases ago we moved to a system that outputs all the required files into a folder (`build` or one of your choice using the `--output-dir` flag).
We won't reintroduce that flag, so I invite you to either use `--output-dir` and have a cleanup script to be called after your CLI operations or to embrace this behaviour.
Hope it's not too much of an inconvenience, but at least this doesn't break when a 3rd party developer does things their way without reading documentation  😬
